go.property("move_direction", vmath.vector3())
go.property("move_distance", 100)
go.property("move_speed", 20)
go.property("is_bot", false)

local TRIGGER_RESPONSE = hash("trigger_response")
local PLAYER_GROUP = hash("player")

function init(self)
	local pos = go.get_position()
	local to = pos + (self.move_direction * self.move_distance)
	local duration =  self.move_distance / self.move_speed

	go.animate(".", "position", go.PLAYBACK_LOOP_PINGPONG, to, go.EASING_LINEAR, duration)

	if self.is_bot then
		sprite.play_flipbook("#sprite", "enemy_bot")
	end

	-- go.animate(".", "position", go.PLAYBACK_LOOP_PINGPONG, to, go.EASING_LINEAR, duration, self.move_speed, complete_function)
	-- go.animate(".", "position", go.PLAYBACK_LOOP_PINGPONG, to, go.EASING_LINEAR, duration, self.move_speed, vmath.vector3())
end

function on_message(self, message_id, message, sender)
	if message_id == TRIGGER_RESPONSE and message.group == PLAYER_GROUP then
		sound.play("#sound_die")
		-- print("sender.group is:", sender) -- sender.group is:	url: [level1:/enemy#collisionobject]
		msg.post("game_controller:/gc#game_controller", "reload_level")
	end
end
