local MOVE_SPEED = 100

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_camera_projection")

	self.velocity = vmath.vector3()
	-- 	msg.post("house_door#door", "init_message", { text = "Player initiated!", score = self.score })

	-- local pos = go.get_position()
	-- print(pos)
	
	-- local new_pos = vmath.vector3(50, 50, 0)
	-- go.set_position(new_pos)
end

function final(self)

end

-- function update(self, dt)
-- -- 	-- dt - dt stands for delta time
-- -- 	local pos = go.get_position()
-- -- 	if pos.x < 500 then
-- -- 		-- pos.x = pos.x + 1 * dt
-- -- 		-- pos.y = pos.y + 1 * dt
-- -- 		pos = pos + vmath.vector3(10, 10, 0) * dt
-- -- 		go.set_position(pos)
-- -- 
-- -- 		local scale = go.get_scale()
-- -- 		if scale.x < 15 then
-- -- 			scale = scale + vmath.vector3(1, 1, 1) * dt * 3
-- -- 			go.set_scale(scale)
-- -- 			-- local rot = go.get_rotation()
-- -- 		end
-- -- 		
-- -- 	end
-- end

function fixed_update(self, dt)
	local pos = go.get_position()
	pos = pos + self.velocity * MOVE_SPEED * dt
	go.set_position(pos)

	self.velocity = vmath.vector3()
end

local function increase_scale()
	local scale = go.get_scale()
	scale = scale + vmath.vector3(0.5, 0.5, 0.5)
	go.set_scale(scale)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("collect_coin") then
		print("coin collected!")
		increase_scale()
	end
end

-- function do_movement(self, action)
-- 	local pos = go.get_position()
-- 	if action == "move_up" then
-- 		pos.y = pos.y + 1
-- 	elseif action == "move_down" then
-- 		pos.y = pos.y - 1
-- 	elseif action == "move_left" then
-- 		pos.x = pos.x - 1
-- 	elseif action == "move_right" then
-- 		pos.x = pos.x + 1
-- 	end
-- 	go.set_position(pos)
-- end

function on_input(self, action_id, action)
	-- if action_id == hash("move_up") then
	-- 	do_movement(self, "move_up")
	-- elseif action_id == hash("move_down") then
	-- 	do_movement(self, "move_down")
	-- elseif action_id == hash("move_left") then
	-- 	do_movement(self, "move_left")
	-- elseif action_id == hash("move_right") then
	-- 	do_movement(self, "move_right")
	-- end
	
	if action_id == hash("move_up") then
		self.velocity.y = 1
	elseif action_id == hash("move_down") then
		self.velocity.y = -1
	end
	
	if action_id == hash("move_left") then
		self.velocity.x = -1
	elseif action_id == hash("move_right") then
		self.velocity.x = 1
	end
end
