function init(self)
	msg.post(".", "acquire_input_focus")
	-- 	print("self is: ")
	-- 	print(self)
	-- 	self.score = 0
	-- 	self.score = self.score + 50
	-- 	if self.score >= 50 then
	-- 		print("init score is: "..self.score)
	-- 	end
	-- 	msg.post("house_door#door", "init_message", { text = "Player initiated!", score = self.score })
end

function final(self)
	print("final score is: "..self.score)
end

function update(self, dt)
	-- print("update")
end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	if message_id == hash("acquire_input_focus") then
		print("get it message")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("get it pressed!")
	end

end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
