function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_camera_projection")
	-- 	msg.post("house_door#door", "init_message", { text = "Player initiated!", score = self.score })

	-- local pos = go.get_position()
	-- print(pos)
	
	-- local new_pos = vmath.vector3(50, 50, 0)
	-- go.set_position(new_pos)
end

function final(self)

end

function update(self, dt)
-- 	-- dt - dt stands for delta time
-- 	local pos = go.get_position()
-- 	if pos.x < 500 then
-- 		-- pos.x = pos.x + 1 * dt
-- 		-- pos.y = pos.y + 1 * dt
-- 		pos = pos + vmath.vector3(10, 10, 0) * dt
-- 		go.set_position(pos)
-- 
-- 		local scale = go.get_scale()
-- 		if scale.x < 15 then
-- 			scale = scale + vmath.vector3(1, 1, 1) * dt * 3
-- 			go.set_scale(scale)
-- 			-- local rot = go.get_rotation()
-- 		end
-- 		
-- 	end
end

function fixed_update(self, dt)
	
end

function on_message(self, message_id, message, sender)
	if message_id == hash("acquire_input_focus") then
		print("get it message")
	end
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		print("get it pressed!")
	end

end

function on_reload(self)

end
